<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>SoueiKakuPopFontMod</AssemblyName>
    <RootNamespace>SoueiKakuPopFontMod</RootNamespace>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <ResonitePath>D:\SteamLibrary\steamapps\common\Resonite</ResonitePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(ResonitePath)\rml_libs\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Elements.Assets">
      <HintPath>$(ResonitePath)\Elements.Assets.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Elements.Core">
      <HintPath>$(ResonitePath)\Elements.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FrooxEngine">
      <HintPath>$(ResonitePath)\FrooxEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ResoniteModLoader">
      <HintPath>$(ResonitePath)\Libraries\ResoniteModLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="DeployToResoniteModFolder" AfterTargets="Build">
    <MakeDir Directories="$(ResonitePath)\rml_mods" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ResonitePath)\rml_mods" />
  </Target>
</Project>
